// The rich crow rotates per loop — each iteration of the cycle
// brings a new "founder" pitching the same scheme. Cast is
// indexed by (loop - 1) modulo the list length, so loop 1 always
// gets Benjamin Peck and the list cycles from there.
export interface RichCast {
  name: string;
  company: string;
}

export const RICH_CASTS: readonly RichCast[] = [
  { name: 'Benjamin Peck', company: 'Crow Automation Systems' },
  { name: 'Margaret Caw', company: 'Caw Labs' },
  { name: 'Edgar Crowford', company: 'Crowford Cortex' },
  { name: 'Olivia Beakerson', company: 'Beaknet' },
  { name: 'Marcus Talon', company: 'Talonchain' },
  { name: 'Felicity Plume', company: 'Plume Intelligence' },
  { name: 'Cordelia Rookwood', company: 'Rookpilot AI' },
  { name: 'Bartholomew Quill', company: 'Quillbrain' },
  { name: 'Penelope Blackwing', company: 'Murmurate' },
  { name: 'Augustus Featherstone', company: 'Featheragent' },
  { name: 'Cassandra Nestor', company: 'Nestor Intelligence' },
  { name: 'Theodore Corvus', company: 'Corvex Robotics' },
  { name: 'Ophelia Pinion', company: 'Pinionflow AI' },
  { name: 'Quentin Cawthorne', company: 'Cawcortex' },
  { name: 'Beatrice Wingate', company: 'Wingspan AI' },
  { name: 'Maximilian Beakwell', company: 'Beakwell Automation' },
  { name: 'Genevieve Crowhurst', company: 'Crowhurst Robotics' },
  { name: 'Reginald Ravensworth', company: 'Ravenmind' },
  { name: 'Constance Pluck', company: 'Pluckpilot' },
  { name: 'Percival Talonworth', company: 'Talonbrain' },
  { name: 'Vivienne Plumage', company: 'Plumage AI Labs' },
  { name: 'Sebastian Wingfield', company: 'Wingfield Automation' },
  { name: 'Henrietta Beakworth', company: 'Beakforge AI' },
  { name: 'Atticus Crowston', company: 'Crowston Cortex' },
  { name: 'Lavinia Rookhaven', company: 'Rookhaven Labs' },
  { name: 'Octavius Featherly', company: 'Featherly Robotics' },
  { name: 'Rosalind Talonford', company: 'Talonbot' },
  { name: 'Cornelius Beakford', company: 'Beakpilot' },
  { name: 'Imogen Plumeworth', company: 'Plumebot' },
  { name: 'Aloysius Crowbridge', company: 'Crowbridge AI' },
  { name: 'Dorothea Pinionford', company: 'Pinionbrain' },
  { name: 'Phineas Ravenswood', company: 'Ravenagent' },
  { name: 'Adelaide Quillstone', company: 'Quillsense' },
  { name: 'Hugo Cawston', company: 'Cawston Automation' },
  { name: 'Eleanora Beakridge', company: 'Beakridge Intelligence' },
  { name: 'Silas Rookley', company: 'Rookley Robotics' },
  { name: 'Wilhelmina Ravenscroft', company: 'Ravenscroft AI' },
  { name: 'Caspian Talonsworth', company: 'Talonsynth' },
  { name: 'Beatrix Corbin', company: 'Corbin AI' },
  { name: 'Algernon Brennan', company: 'Brennan Labs' },
  { name: 'Prudence Branwen', company: 'Branwen Automation' },
  { name: 'Bertram Crowe', company: 'Crowe Robotics' },
  { name: 'Saskia Quillsworth', company: 'Quillpilot' },
  { name: 'Mortimer Beakwright', company: 'Beakwright Intelligence' },
  { name: 'Lucinda Crowley', company: 'Crowley AI' },
  { name: 'Horatio Pinionhurst', company: 'Pinionsynth' },
  { name: 'Clementine Beakhurst', company: 'Beakhurst Automation' },
  { name: 'Ezekiel Quillon', company: 'Quillon Robotics' },
  { name: 'Tabitha Beakston', company: 'Beakston AI' },
  { name: 'Jasper Crowsmith', company: 'Crowsmith Cortex' },
  { name: 'Magdalena Beaksmith', company: 'Beaksmith Labs' },
  { name: 'Leopold Cawsmith', company: 'Cawsmith Robotics' },
  { name: 'Persephone Rooksmith', company: 'Rooksmith Intelligence' },
  { name: 'Ambrose Talonsmith', company: 'Talonsmith Automation' },
  { name: 'Seraphina Plumesmith', company: 'Plumesmith AI' },
  { name: 'Crispin Featherwood', company: 'Featherwood Robotics' },
  { name: 'Antonia Crowwood', company: 'Crowwood AI' },
  { name: 'Roderick Beakwood', company: 'Beakwood Intelligence' },
  { name: 'Gwendolyn Talonwood', company: 'Talonwood Automation' },
  { name: 'Florian Pinionwood', company: 'Pinionwood AI' },
  { name: 'Hyacinth Quillwood', company: 'Quillwood Robotics' },
  { name: 'Otis Crowfield', company: 'Crowfield Cortex' },
  { name: 'Cecily Beakfield', company: 'Beakfield Brain' },
  { name: 'Rupert Talonfield', company: 'Talonfield AI' },
  { name: 'Drusilla Rookfield', company: 'Rookfield Automation' },
  { name: 'Wendell Plumefield', company: 'Plumefield Intelligence' },
  { name: 'Cosima Featherfield', company: 'Featherfield AI' },
  { name: 'Ignatius Crowmore', company: 'Crowmore Robotics' },
  { name: 'Briony Beakmore', company: 'Beakmore Labs' },
  { name: 'Honoria Talonmore', company: 'Talonmore Cortex' },
  { name: 'Hubert Rookmore', company: 'Rookmore AI' },
  { name: 'Araminta Plumemore', company: 'Plumemore Automation' },
  { name: 'Eustace Crowham', company: 'Crowham Intelligence' },
  { name: 'Calliope Beakham', company: 'Beakham AI' },
  { name: 'Llewellyn Talonham', company: 'Talonham Robotics' },
  { name: 'Dashiell Rookham', company: 'Rookham AI' },
  { name: 'Millicent Crowdale', company: 'Crowdale Automation' },
  { name: 'Frederick Beakdale', company: 'Beakdale AI' },
  { name: 'Iolanthe Talondale', company: 'Talondale Cortex' },
  { name: 'Barnaby Rookdale', company: 'Rookdale AI' },
  { name: 'Cosmo Plumedale', company: 'Plumedale Brain' },
  { name: 'Lucasta Beakley', company: 'Beakley Automation' },
  { name: 'Tristan Talonley', company: 'Talonley AI' },
  { name: 'Octavia Crowstone', company: 'Crowstone Robotics' },
  { name: 'Caius Beakstone', company: 'Beakstone AI' },
  { name: 'Sybilla Talonstone', company: 'Talonstone Intelligence' },
  { name: 'Thaddeus Rookstone', company: 'Rookstone Automation' },
  { name: 'Hortense Plumestone', company: 'Plumestone AI' },
  { name: 'Edmund Pinionham', company: 'Pinionham Cortex' },
  { name: 'Lysandra Cawford', company: 'Cawford AI' },
  { name: 'Roland Pinionhart', company: 'Pinionhart Robotics' },
  { name: 'Esmerelda Cawhurst', company: 'Cawhurst Labs' },
  { name: 'Hieronymus Plumehart', company: 'Plumehart Brain' },
  { name: 'Vesper Rookhurst', company: 'Rookhurst Automation' },
  { name: 'Casimir Talonhurst', company: 'Talonhurst AI' },
  { name: 'Beulah Featherhurst', company: 'Featherhurst Intelligence' },
  { name: 'Percy Quillham', company: 'Quillham AI' },
  { name: 'Maeve Featherton', company: 'Featherton Automation' },
  { name: 'Wallace Beakton', company: 'Beakton AI' },
  { name: 'Loretta Talonton', company: 'Talonton Cortex' },
  { name: 'Cyrus Crowby', company: 'Crowby AI' },
  { name: 'Mathilda Beakby', company: 'Beakby Robotics' },
  { name: 'Egmont Talonby', company: 'Talonby AI' },
  { name: 'Verity Rookby', company: 'Rookby Automation' },
  { name: 'Galen Plumeby', company: 'Plumeby AI' },
  { name: 'Henrika Cawby', company: 'Cawby Intelligence' },
];

export function getRichCast(loop: number): RichCast {
  return RICH_CASTS[(loop - 1) % RICH_CASTS.length];
}
