// The rich crow rotates per loop — each iteration of the cycle
// brings a new "founder" pitching the same scheme. Cast is
// indexed by (loop - 1) modulo the list length, so loop 1 always
// gets Benjamin Peck and the list cycles from there. The product
// rotates alongside the founder — same robot crow visual, fresh
// marketing label each loop.
export interface RichCast {
  name: string;
  company: string;
  product: string;
}

export const RICH_CASTS: readonly RichCast[] = [
  { name: 'Benjamin Peck', company: 'Crow Automation Systems', product: 'Robo-Crow' },
  { name: 'Margaret Caw', company: 'Caw Labs', product: 'Caw-Bot' },
  { name: 'Edgar Crowford', company: 'Crowford Cortex', product: 'Mecha-Crowford' },
  { name: 'Olivia Beakerson', company: 'Beaknet', product: 'BeakDroid' },
  { name: 'Marcus Talon', company: 'Talonchain', product: 'Talon-Tron' },
  { name: 'Felicity Plume', company: 'Plume Intelligence', product: 'Plume Automaton' },
  { name: 'Cordelia Rookwood', company: 'Rookpilot AI', product: 'Rook-Mech' },
  { name: 'Bartholomew Quill', company: 'Quillbrain', product: 'Quill-Bot 9000' },
  { name: 'Penelope Blackwing', company: 'Murmurate', product: 'Murmur Mk II' },
  { name: 'Augustus Featherstone', company: 'Featheragent', product: 'Feather-Droid' },
  { name: 'Cassandra Nestor', company: 'Nestor Intelligence', product: 'Servo-Nestor' },
  { name: 'Theodore Corvus', company: 'Corvex Robotics', product: 'Corvex-7' },
  { name: 'Ophelia Pinion', company: 'Pinionflow AI', product: 'Pinion-Bot' },
  { name: 'Quentin Cawthorne', company: 'Cawcortex', product: 'CawTron' },
  { name: 'Beatrice Wingate', company: 'Wingspan AI', product: 'Wingspan Mk III' },
  { name: 'Maximilian Beakwell', company: 'Beakwell Automation', product: 'Auto-Beak' },
  { name: 'Genevieve Crowhurst', company: 'Crowhurst Robotics', product: 'CrowBot 3000' },
  { name: 'Reginald Ravensworth', company: 'Ravenmind', product: 'Raven-Droid' },
  { name: 'Constance Pluck', company: 'Pluckpilot', product: 'Pluck-Mech' },
  { name: 'Percival Talonworth', company: 'Talonbrain', product: 'Talon Automaton' },
  { name: 'Vivienne Plumage', company: 'Plumage AI Labs', product: 'Plume-Tron' },
  { name: 'Sebastian Wingfield', company: 'Wingfield Automation', product: 'Auto-Wing' },
  { name: 'Henrietta Beakworth', company: 'Beakforge AI', product: 'BeakForge Droid' },
  { name: 'Atticus Crowston', company: 'Crowston Cortex', product: 'Crowston-Mech' },
  { name: 'Lavinia Rookhaven', company: 'Rookhaven Labs', product: 'RookHaven Bot' },
  { name: 'Octavius Featherly', company: 'Featherly Robotics', product: 'FeatherBot' },
  { name: 'Rosalind Talonford', company: 'Talonbot', product: 'Talonbot Mini' },
  { name: 'Cornelius Beakford', company: 'Beakpilot', product: 'Beak Mk II' },
  { name: 'Imogen Plumeworth', company: 'Plumebot', product: 'PlumeBot Mini' },
  { name: 'Aloysius Crowbridge', company: 'Crowbridge AI', product: 'Crowbridge Automaton' },
  { name: 'Dorothea Pinionford', company: 'Pinionbrain', product: 'Pinion-Tron' },
  { name: 'Phineas Ravenswood', company: 'Ravenagent', product: 'Raven-Bot' },
  { name: 'Adelaide Quillstone', company: 'Quillsense', product: 'Quill-Droid' },
  { name: 'Hugo Cawston', company: 'Cawston Automation', product: 'Auto-Caw' },
  { name: 'Eleanora Beakridge', company: 'Beakridge Intelligence', product: 'Mecha-Beakridge' },
  { name: 'Silas Rookley', company: 'Rookley Robotics', product: 'RookBot 9' },
  { name: 'Wilhelmina Ravenscroft', company: 'Ravenscroft AI', product: 'Ravenscroft Droid' },
  { name: 'Caspian Talonsworth', company: 'Talonsynth', product: 'Synth-Talon Bot' },
  { name: 'Beatrix Corbin', company: 'Corbin AI', product: 'Corbin-Tron' },
  { name: 'Algernon Brennan', company: 'Brennan Labs', product: 'Brennan-Bot' },
  { name: 'Prudence Branwen', company: 'Branwen Automation', product: 'Auto-Branwen' },
  { name: 'Bertram Crowe', company: 'Crowe Robotics', product: 'CroweBot' },
  { name: 'Saskia Quillsworth', company: 'Quillpilot', product: 'Quill-Mech' },
  { name: 'Mortimer Beakwright', company: 'Beakwright Intelligence', product: 'BeakWright Mecha' },
  { name: 'Lucinda Crowley', company: 'Crowley AI', product: 'Crowley-Tron' },
  { name: 'Horatio Pinionhurst', company: 'Pinionsynth', product: 'Synth-Pinion Droid' },
  { name: 'Clementine Beakhurst', company: 'Beakhurst Automation', product: 'Auto-BeakHurst' },
  { name: 'Ezekiel Quillon', company: 'Quillon Robotics', product: 'QuillOn Bot' },
  { name: 'Tabitha Beakston', company: 'Beakston AI', product: 'BeakSton Mk II' },
  { name: 'Jasper Crowsmith', company: 'Crowsmith Cortex', product: 'Crowsmith Mk VII' },
  { name: 'Magdalena Beaksmith', company: 'Beaksmith Labs', product: 'BeakSmith Droid' },
  { name: 'Leopold Cawsmith', company: 'Cawsmith Robotics', product: 'CawSmith Bot' },
  { name: 'Persephone Rooksmith', company: 'Rooksmith Intelligence', product: 'RookSmith Mecha' },
  { name: 'Ambrose Talonsmith', company: 'Talonsmith Automation', product: 'Auto-TalonSmith' },
  { name: 'Seraphina Plumesmith', company: 'Plumesmith AI', product: 'PlumeSmith-Tron' },
  { name: 'Crispin Featherwood', company: 'Featherwood Robotics', product: 'FeatherWood Bot' },
  { name: 'Antonia Crowwood', company: 'Crowwood AI', product: 'Mecha-CrowWood' },
  { name: 'Roderick Beakwood', company: 'Beakwood Intelligence', product: 'BeakWood Droid' },
  { name: 'Gwendolyn Talonwood', company: 'Talonwood Automation', product: 'Auto-TalonWood' },
  { name: 'Florian Pinionwood', company: 'Pinionwood AI', product: 'PinionWood Bot' },
  { name: 'Hyacinth Quillwood', company: 'Quillwood Robotics', product: 'QuillWood Mk II' },
  { name: 'Otis Crowfield', company: 'Crowfield Cortex', product: 'CrowField Automaton' },
  { name: 'Cecily Beakfield', company: 'Beakfield Brain', product: 'BeakField Bot' },
  { name: 'Rupert Talonfield', company: 'Talonfield AI', product: 'TalonField-Tron' },
  { name: 'Drusilla Rookfield', company: 'Rookfield Automation', product: 'Auto-RookField' },
  { name: 'Wendell Plumefield', company: 'Plumefield Intelligence', product: 'PlumeField Mecha' },
  { name: 'Cosima Featherfield', company: 'Featherfield AI', product: 'FeatherField Droid' },
  { name: 'Ignatius Crowmore', company: 'Crowmore Robotics', product: 'CrowMore-X' },
  { name: 'Briony Beakmore', company: 'Beakmore Labs', product: 'BeakMore Bot' },
  { name: 'Honoria Talonmore', company: 'Talonmore Cortex', product: 'TalonMore Mecha' },
  { name: 'Hubert Rookmore', company: 'Rookmore AI', product: 'RookMore-Tron' },
  { name: 'Araminta Plumemore', company: 'Plumemore Automation', product: 'Auto-PlumeMore' },
  { name: 'Eustace Crowham', company: 'Crowham Intelligence', product: 'CrowHam Droid' },
  { name: 'Calliope Beakham', company: 'Beakham AI', product: 'BeakHam Bot' },
  { name: 'Llewellyn Talonham', company: 'Talonham Robotics', product: 'TalonHam Mecha' },
  { name: 'Dashiell Rookham', company: 'Rookham AI', product: 'RookHam-7' },
  { name: 'Millicent Crowdale', company: 'Crowdale Automation', product: 'Auto-CrowDale' },
  { name: 'Frederick Beakdale', company: 'Beakdale AI', product: 'BeakDale Droid' },
  { name: 'Iolanthe Talondale', company: 'Talondale Cortex', product: 'TalonDale Mk III' },
  { name: 'Barnaby Rookdale', company: 'Rookdale AI', product: 'RookDale-2' },
  { name: 'Cosmo Plumedale', company: 'Plumedale Brain', product: 'PlumeDale Bot' },
  { name: 'Lucasta Beakley', company: 'Beakley Automation', product: 'Auto-BeakLey' },
  { name: 'Tristan Talonley', company: 'Talonley AI', product: 'TalonLey-Tron' },
  { name: 'Octavia Crowstone', company: 'Crowstone Robotics', product: 'CrowStone Bot' },
  { name: 'Caius Beakstone', company: 'Beakstone AI', product: 'BeakStone Mecha' },
  { name: 'Sybilla Talonstone', company: 'Talonstone Intelligence', product: 'TalonStone Droid' },
  { name: 'Thaddeus Rookstone', company: 'Rookstone Automation', product: 'Auto-RookStone' },
  { name: 'Hortense Plumestone', company: 'Plumestone AI', product: 'PlumeStone Bot' },
  { name: 'Edmund Pinionham', company: 'Pinionham Cortex', product: 'PinionHam Mecha' },
  { name: 'Lysandra Cawford', company: 'Cawford AI', product: 'Cawford-Tron' },
  { name: 'Roland Pinionhart', company: 'Pinionhart Robotics', product: 'PinionHart Bot' },
  { name: 'Esmerelda Cawhurst', company: 'Cawhurst Labs', product: 'CawHurst Droid' },
  { name: 'Hieronymus Plumehart', company: 'Plumehart Brain', product: 'PlumeHart Mecha' },
  { name: 'Vesper Rookhurst', company: 'Rookhurst Automation', product: 'Auto-RookHurst' },
  { name: 'Casimir Talonhurst', company: 'Talonhurst AI', product: 'TalonHurst-Tron' },
  { name: 'Beulah Featherhurst', company: 'Featherhurst Intelligence', product: 'FeatherHurst Bot' },
  { name: 'Percy Quillham', company: 'Quillham AI', product: 'QuillHam Droid' },
  { name: 'Maeve Featherton', company: 'Featherton Automation', product: 'Auto-FeatherTon' },
  { name: 'Wallace Beakton', company: 'Beakton AI', product: 'BeakTon Bot' },
  { name: 'Loretta Talonton', company: 'Talonton Cortex', product: 'TalonTon Mecha' },
  { name: 'Cyrus Crowby', company: 'Crowby AI', product: 'Crowby-Tron' },
  { name: 'Mathilda Beakby', company: 'Beakby Robotics', product: 'BeakBy Bot' },
  { name: 'Egmont Talonby', company: 'Talonby AI', product: 'TalonBy Droid' },
  { name: 'Verity Rookby', company: 'Rookby Automation', product: 'Auto-RookBy' },
  { name: 'Galen Plumeby', company: 'Plumeby AI', product: 'PlumeBy Mk II' },
  { name: 'Henrika Cawby', company: 'Cawby Intelligence', product: 'CawBy Automaton' },
];

export function getRichCast(loop: number): RichCast {
  return RICH_CASTS[(loop - 1) % RICH_CASTS.length];
}
